---
title: 在 .NET 中處理 I/O 錯誤
description: 瞭解如何在 .NET 中處理 i/o 錯誤。 將錯誤碼對應至例外狀況、處理 i/o 作業中的例外狀況，以及處理 IOException。
ms.date: 08/27/2018
dev_langs:
- csharp
- vb
helpviewer_keywords:
- I/O, exception handling
- I/O, errors
ms.workload:
- dotnet
- dotnetcore
ms.openlocfilehash: fe6796be91d31e3f7bf69605f39a39f3db6b3e83
ms.sourcegitcommit: 965a5af7918acb0a3fd3baf342e15d511ef75188
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 11/18/2020
ms.locfileid: "94830866"
---
# <a name="handling-io-errors-in-net"></a><span data-ttu-id="da4cb-104">在 .NET 中處理 I/O 錯誤</span><span class="sxs-lookup"><span data-stu-id="da4cb-104">Handling I/O errors in .NET</span></span>

<span data-ttu-id="da4cb-105">除了在任何方法呼叫中擲回的例外狀況以外 (例如系統負荷過高造成的 <xref:System.OutOfMemoryException>，或程式設計人員出錯造成的 <xref:System.NullReferenceException>)，.NET 檔案系統方法還會擲回下列例外狀況：</span><span class="sxs-lookup"><span data-stu-id="da4cb-105">In addition to the exceptions that can be thrown in any method call (such as an <xref:System.OutOfMemoryException> when a system is stressed or an <xref:System.NullReferenceException> due to programmer error), .NET file system methods can throw the following exceptions:</span></span>

- <span data-ttu-id="da4cb-106"><xref:System.IO.IOException?displayProperty=nameWithType>，所有 <xref:System.IO> 例外狀況類型的基底類別。</span><span class="sxs-lookup"><span data-stu-id="da4cb-106"><xref:System.IO.IOException?displayProperty=nameWithType>, the base class of all <xref:System.IO> exception types.</span></span> <span data-ttu-id="da4cb-107">之所以會擲回此例外狀況，是因為來自作業系統的錯誤傳回碼沒有直接對應到任何其他例外狀況類型。</span><span class="sxs-lookup"><span data-stu-id="da4cb-107">It is thrown for errors whose return codes from the operating system don't directly map to any other exception type.</span></span>
- <span data-ttu-id="da4cb-108"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="da4cb-108"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="da4cb-109"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="da4cb-109"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="da4cb-110"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="da4cb-110"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="da4cb-111"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="da4cb-111"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="da4cb-112"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="da4cb-112"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="da4cb-113"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="da4cb-113"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="da4cb-114"><xref:System.ArgumentException?displayProperty=nameWithType>，針對 .NET Framework 和 .NET Core 2.0 及更早版本上的無效路徑字元擲回。</span><span class="sxs-lookup"><span data-stu-id="da4cb-114"><xref:System.ArgumentException?displayProperty=nameWithType>, which is thrown for invalid path characters on .NET Framework and on .NET Core 2.0 and previous versions.</span></span>
- <span data-ttu-id="da4cb-115"><xref:System.NotSupportedException?displayProperty=nameWithType>，針對 .NET Framework 中的無效冒號擲回。</span><span class="sxs-lookup"><span data-stu-id="da4cb-115"><xref:System.NotSupportedException?displayProperty=nameWithType>, which is thrown for invalid colons in .NET Framework.</span></span>
- <span data-ttu-id="da4cb-116"><xref:System.Security.SecurityException?displayProperty=nameWithType>，此例外狀況是因為應用程式在有限信任中執行而擲回，其缺少僅在 .NET Framework 上適用的必要權限。</span><span class="sxs-lookup"><span data-stu-id="da4cb-116"><xref:System.Security.SecurityException?displayProperty=nameWithType>, which is thrown for applications running in limited trust that lack the necessary permissions on .NET Framework only.</span></span> <span data-ttu-id="da4cb-117">(.NET Framework 上預設是完全信任。)</span><span class="sxs-lookup"><span data-stu-id="da4cb-117">(Full trust is the default on .NET Framework.)</span></span>

## <a name="mapping-error-codes-to-exceptions"></a><span data-ttu-id="da4cb-118">將錯誤碼對應至例外狀況</span><span class="sxs-lookup"><span data-stu-id="da4cb-118">Mapping error codes to exceptions</span></span>

<span data-ttu-id="da4cb-119">因為檔案系統是作業系統資源，所以 .NET Core 和 .NET Framework 兩者中的 I/O 方法會將呼叫包裝至基礎作業系統。</span><span class="sxs-lookup"><span data-stu-id="da4cb-119">Because the file system is an operating system resource, I/O methods in both .NET Core and .NET Framework wrap calls to the underlying operating system.</span></span> <span data-ttu-id="da4cb-120">在作業系統所執行的程式碼中發生 I/O 錯誤時，作業系統會將錯誤資訊傳回給 .NET I/O 方法。</span><span class="sxs-lookup"><span data-stu-id="da4cb-120">When an I/O error occurs in code executed by the operating system, the operating system returns error information to the .NET I/O method.</span></span> <span data-ttu-id="da4cb-121">接著方法會將錯誤資訊 (通常是錯誤碼的形式) 轉譯為 .NET 例外狀況類型。</span><span class="sxs-lookup"><span data-stu-id="da4cb-121">The method then translates the error information, typically in the form of an error code, into a .NET exception type.</span></span> <span data-ttu-id="da4cb-122">在大部分情況下，這個作業是藉由直接將錯誤碼轉譯為其對應例外狀況類型來完成；不會根據方法呼叫的內容來執行任何特殊的錯誤對應。</span><span class="sxs-lookup"><span data-stu-id="da4cb-122">In most cases, it does this by directly translating the error code into its corresponding exception type; it does not perform any special mapping of the error based on the context of the method call.</span></span>

<span data-ttu-id="da4cb-123">例如在 Windows 作業系統上，傳回 `ERROR_FILE_NOT_FOUND` 錯誤碼 (或 0x02) 的方法呼叫會對應至 <xref:System.IO.FileNotFoundException>，傳回 `ERROR_PATH_NOT_FOUND` 錯誤碼 (或 0x03) 的方法呼叫會對應至 <xref:System.IO.DirectoryNotFoundException>。</span><span class="sxs-lookup"><span data-stu-id="da4cb-123">For example, on the Windows operating system, a method call that returns an error code of `ERROR_FILE_NOT_FOUND` (or 0x02) maps to a <xref:System.IO.FileNotFoundException>, and an error code of `ERROR_PATH_NOT_FOUND` (or 0x03) maps to a <xref:System.IO.DirectoryNotFoundException>.</span></span>

<span data-ttu-id="da4cb-124">不過，作業系統會傳回特定錯誤碼的精確條件，通常未記載或記載不佳。</span><span class="sxs-lookup"><span data-stu-id="da4cb-124">However, the precise conditions under which the operating system returns particular error codes is often undocumented or poorly documented.</span></span> <span data-ttu-id="da4cb-125">因此會發生未預期的例外狀況。</span><span class="sxs-lookup"><span data-stu-id="da4cb-125">As a result, unexpected exceptions can occur.</span></span> <span data-ttu-id="da4cb-126">例如，因為您使用目錄而不是檔案，您可預期對 <xref:System.IO.DirectoryInfo.%23ctor%2A> 建構函式提供無效的目錄路徑會擲回 <xref:System.IO.DirectoryNotFoundException>。</span><span class="sxs-lookup"><span data-stu-id="da4cb-126">For example, because you are working with a directory rather than a file, you would expect that providing an invalid directory path to the <xref:System.IO.DirectoryInfo.%23ctor%2A> constructor throws a <xref:System.IO.DirectoryNotFoundException>.</span></span> <span data-ttu-id="da4cb-127">不過，它也可能會擲回 <xref:System.IO.FileNotFoundException>。</span><span class="sxs-lookup"><span data-stu-id="da4cb-127">However, it may also throw a <xref:System.IO.FileNotFoundException>.</span></span>

## <a name="exception-handling-in-io-operations"></a><span data-ttu-id="da4cb-128">I/O 作業中的例外狀況處理</span><span class="sxs-lookup"><span data-stu-id="da4cb-128">Exception handling in I/O operations</span></span>

<span data-ttu-id="da4cb-129">因為必須依賴作業系統，所以相同的例外狀況 (例如我們範例中的找不到目錄錯誤) 會導致 I/O 方法擲回 I/O 例外狀況的任何一個完整類別。</span><span class="sxs-lookup"><span data-stu-id="da4cb-129">Because of this reliance on the operating system, identical exception conditions (such as the directory not found error in our example) can result in an I/O method throwing any one of the entire class of I/O exceptions.</span></span> <span data-ttu-id="da4cb-130">這表示在呼叫 I/O API 時，您的程式碼應該已準備好處理大部分或所有例外狀況，如下表所示：</span><span class="sxs-lookup"><span data-stu-id="da4cb-130">This means that, when calling I/O APIs, your code should be prepared to handle most or all of these exceptions, as shown in the following table:</span></span>

| <span data-ttu-id="da4cb-131">例外狀況類型</span><span class="sxs-lookup"><span data-stu-id="da4cb-131">Exception type</span></span> | <span data-ttu-id="da4cb-132">.NET Core/. NET 5 +</span><span class="sxs-lookup"><span data-stu-id="da4cb-132">.NET Core/.NET 5+</span></span> | <span data-ttu-id="da4cb-133">.NET Framework</span><span class="sxs-lookup"><span data-stu-id="da4cb-133">.NET Framework</span></span> |
|---|---|---|
| <xref:System.IO.IOException> | <span data-ttu-id="da4cb-134">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-134">Yes</span></span> | <span data-ttu-id="da4cb-135">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-135">Yes</span></span> |
| <xref:System.IO.FileNotFoundException> | <span data-ttu-id="da4cb-136">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-136">Yes</span></span> | <span data-ttu-id="da4cb-137">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-137">Yes</span></span> |
| <xref:System.IO.DirectoryNotFoundException> | <span data-ttu-id="da4cb-138">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-138">Yes</span></span> | <span data-ttu-id="da4cb-139">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-139">Yes</span></span> |
| <xref:System.IO.DriveNotFoundException?> | <span data-ttu-id="da4cb-140">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-140">Yes</span></span> | <span data-ttu-id="da4cb-141">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-141">Yes</span></span> |
| <xref:System.IO.PathTooLongException> | <span data-ttu-id="da4cb-142">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-142">Yes</span></span> | <span data-ttu-id="da4cb-143">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-143">Yes</span></span> |
| <xref:System.OperationCanceledException> | <span data-ttu-id="da4cb-144">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-144">Yes</span></span> | <span data-ttu-id="da4cb-145">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-145">Yes</span></span> |
| <xref:System.UnauthorizedAccessException> | <span data-ttu-id="da4cb-146">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-146">Yes</span></span> | <span data-ttu-id="da4cb-147">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-147">Yes</span></span> |
| <xref:System.ArgumentException> | <span data-ttu-id="da4cb-148">.NET Core 2.0 及更早版本</span><span class="sxs-lookup"><span data-stu-id="da4cb-148">.NET Core 2.0 and earlier</span></span>| <span data-ttu-id="da4cb-149">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-149">Yes</span></span> |
| <xref:System.NotSupportedException> | <span data-ttu-id="da4cb-150">否</span><span class="sxs-lookup"><span data-stu-id="da4cb-150">No</span></span> | <span data-ttu-id="da4cb-151">是</span><span class="sxs-lookup"><span data-stu-id="da4cb-151">Yes</span></span> |
| <xref:System.Security.SecurityException> | <span data-ttu-id="da4cb-152">否</span><span class="sxs-lookup"><span data-stu-id="da4cb-152">No</span></span> | <span data-ttu-id="da4cb-153">僅限有限信任</span><span class="sxs-lookup"><span data-stu-id="da4cb-153">Limited trust only</span></span> |

## <a name="handling-ioexception"></a><span data-ttu-id="da4cb-154">處理 IOException</span><span class="sxs-lookup"><span data-stu-id="da4cb-154">Handling IOException</span></span>

<span data-ttu-id="da4cb-155">作為 <xref:System.IO> 命名空間中例外狀況的基底類別，<xref:System.IO.IOException> 也會因為任何錯誤碼未對應至預先定義的例外狀況類型而擲回。</span><span class="sxs-lookup"><span data-stu-id="da4cb-155">As the base class for exceptions in the <xref:System.IO> namespace, <xref:System.IO.IOException> is also thrown for any error code that does not map to a predefined exception type.</span></span> <span data-ttu-id="da4cb-156">這表示此例外狀況可由任何 I/O 作業擲回。</span><span class="sxs-lookup"><span data-stu-id="da4cb-156">This means that it can be thrown by any I/O operation.</span></span>

> [!IMPORTANT]
> <span data-ttu-id="da4cb-157">因為 <xref:System.IO.IOException> 是 <xref:System.IO> 命名空間中其他例外狀況類型的基底類別，所以您應該在處理過其他 I/O 相關例外狀況之後，在 `catch` 區塊中處理此例外狀況。</span><span class="sxs-lookup"><span data-stu-id="da4cb-157">Because <xref:System.IO.IOException> is the base class of the other exception types in the <xref:System.IO> namespace, you should handle in a `catch` block after you've handled the other I/O-related exceptions.</span></span>

<span data-ttu-id="da4cb-158">此外，從 .NET Core 2.1 開始，已移除路徑正確性的驗證檢查 (例如，為了確保無效字元不會出現在路徑中)，而且執行階段會從作業系統錯誤碼而非它自己的驗證碼，擲回對應的例外狀況。</span><span class="sxs-lookup"><span data-stu-id="da4cb-158">In addition, starting with .NET Core 2.1, validation checks for path correctness (for example, to ensure that invalid characters are not present in a path) have been removed, and the runtime throws an exception mapped from an operating system error code rather than from its own validation code.</span></span> <span data-ttu-id="da4cb-159">在此情況下最有可能擲回的例外狀況是 <xref:System.IO.IOException>，但是也可能會擲回其他任何例外狀況類型。</span><span class="sxs-lookup"><span data-stu-id="da4cb-159">The most likely exception to be thrown in this case is an <xref:System.IO.IOException>, although any other exception type could also be thrown.</span></span>

<span data-ttu-id="da4cb-160">請注意，在您的例外狀況處理程式碼中，您應該一律最後處理 <xref:System.IO.IOException>。</span><span class="sxs-lookup"><span data-stu-id="da4cb-160">Note that, in your exception handling code, you should always handle the <xref:System.IO.IOException> last.</span></span> <span data-ttu-id="da4cb-161">否則，因為它是其他所有 IO 例外狀況的基底類別，會造成衍生類別的 Catch 區塊不會受到評估。</span><span class="sxs-lookup"><span data-stu-id="da4cb-161">Otherwise, because it is the base class of all other IO exceptions, the catch blocks of derived classes will not be evaluated.</span></span>

<span data-ttu-id="da4cb-162">若是 <xref:System.IO.IOException>，您可以從 [IOException.HResult](xref:System.Exception.HResult) 屬性取得額外的錯誤資訊。</span><span class="sxs-lookup"><span data-stu-id="da4cb-162">In the case of an <xref:System.IO.IOException>, you can get additional error information from the [IOException.HResult](xref:System.Exception.HResult) property.</span></span> <span data-ttu-id="da4cb-163">若要將 HResult 值轉換為 Win32 錯誤碼，您要去除 32 位元值的前 16 位元。</span><span class="sxs-lookup"><span data-stu-id="da4cb-163">To convert the HResult value to a Win32 error code, you strip out the upper 16 bits of the 32-bit value.</span></span> <span data-ttu-id="da4cb-164">下表列出可能包裝在 <xref:System.IO.IOException> 中的錯誤碼。</span><span class="sxs-lookup"><span data-stu-id="da4cb-164">The following table lists error codes that may be wrapped in an <xref:System.IO.IOException>.</span></span>

| <span data-ttu-id="da4cb-165">HResult</span><span class="sxs-lookup"><span data-stu-id="da4cb-165">HResult</span></span> | <span data-ttu-id="da4cb-166">常數</span><span class="sxs-lookup"><span data-stu-id="da4cb-166">Constant</span></span> | <span data-ttu-id="da4cb-167">描述</span><span class="sxs-lookup"><span data-stu-id="da4cb-167">Description</span></span> |
| --- | --- | --- |
| <span data-ttu-id="da4cb-168">ERROR_SHARING_VIOLATION</span><span class="sxs-lookup"><span data-stu-id="da4cb-168">ERROR_SHARING_VIOLATION</span></span> | <span data-ttu-id="da4cb-169">32</span><span class="sxs-lookup"><span data-stu-id="da4cb-169">32</span></span> | <span data-ttu-id="da4cb-170">遺漏檔案名稱，或者檔案或目錄正在使用中。</span><span class="sxs-lookup"><span data-stu-id="da4cb-170">The file name is missing, or the file or directory is in use.</span></span> |
| <span data-ttu-id="da4cb-171">ERROR_FILE_EXISTS</span><span class="sxs-lookup"><span data-stu-id="da4cb-171">ERROR_FILE_EXISTS</span></span> | <span data-ttu-id="da4cb-172">80</span><span class="sxs-lookup"><span data-stu-id="da4cb-172">80</span></span> | <span data-ttu-id="da4cb-173">檔案已存在。</span><span class="sxs-lookup"><span data-stu-id="da4cb-173">The file already exists.</span></span> |
| <span data-ttu-id="da4cb-174">ERROR_INVALID_PARAMETER</span><span class="sxs-lookup"><span data-stu-id="da4cb-174">ERROR_INVALID_PARAMETER</span></span> | <span data-ttu-id="da4cb-175">87</span><span class="sxs-lookup"><span data-stu-id="da4cb-175">87</span></span> | <span data-ttu-id="da4cb-176">提供給方法的引數無效。</span><span class="sxs-lookup"><span data-stu-id="da4cb-176">An argument supplied to the method is invalid.</span></span> |
| <span data-ttu-id="da4cb-177">ERROR_ALREADY_EXISTS</span><span class="sxs-lookup"><span data-stu-id="da4cb-177">ERROR_ALREADY_EXISTS</span></span> | <span data-ttu-id="da4cb-178">183</span><span class="sxs-lookup"><span data-stu-id="da4cb-178">183</span></span> | <span data-ttu-id="da4cb-179">檔案或目錄已存在。</span><span class="sxs-lookup"><span data-stu-id="da4cb-179">The file or directory already exists.</span></span> |

<span data-ttu-id="da4cb-180">您可以在 Catch 陳述式中使用 `When` 子句來進行處理，如下列範例所示。</span><span class="sxs-lookup"><span data-stu-id="da4cb-180">You can handle these using a `When` clause in a catch statement, as the following example shows.</span></span>

[!code-csharp[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/cs/io-exceptions.cs)]
[!code-vb[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/vb/io-exceptions.vb)]

## <a name="see-also"></a><span data-ttu-id="da4cb-181">請參閱</span><span class="sxs-lookup"><span data-stu-id="da4cb-181">See also</span></span>

- [<span data-ttu-id="da4cb-182">在 .NET 中處理和擲回例外狀況</span><span class="sxs-lookup"><span data-stu-id="da4cb-182">Handling and throwing exceptions in .NET</span></span>](../exceptions/index.md)
- [<span data-ttu-id="da4cb-183">例外狀況處理 (工作平行程式庫) </span><span class="sxs-lookup"><span data-stu-id="da4cb-183">Exception handling (Task Parallel Library)</span></span>](../parallel-programming/exception-handling-task-parallel-library.md)
- [<span data-ttu-id="da4cb-184">例外狀況的最佳作法</span><span class="sxs-lookup"><span data-stu-id="da4cb-184">Best practices for exceptions</span></span>](../exceptions/best-practices-for-exceptions.md)
- [<span data-ttu-id="da4cb-185">如何使用 Catch 區塊中的特定例外狀況</span><span class="sxs-lookup"><span data-stu-id="da4cb-185">How to use specific exceptions in a catch block</span></span>](../exceptions/how-to-use-specific-exceptions-in-a-catch-block.md)
