---
title: 例外狀況
ms.date: 03/30/2017
ms.assetid: 065205cc-52dd-4f30-9578-b17d8d113136
ms.openlocfilehash: 53cc8e3e27e131c5c2a9f8271851a0d8d7e0cbd7
ms.sourcegitcommit: bc293b14af795e0e999e3304dd40c0222cf2ffe4
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 11/26/2020
ms.locfileid: "96280204"
---
# <a name="exceptions"></a><span data-ttu-id="38c3d-102">例外狀況</span><span class="sxs-lookup"><span data-stu-id="38c3d-102">Exceptions</span></span>

<span data-ttu-id="38c3d-103">工作流程可以利用 <xref:System.Activities.Statements.TryCatch> 活動處理在工作流程執行期間引發的例外狀況。</span><span class="sxs-lookup"><span data-stu-id="38c3d-103">Workflows can use the <xref:System.Activities.Statements.TryCatch> activity to handle exceptions that are raised during the execution of a workflow.</span></span> <span data-ttu-id="38c3d-104">工作流程可以處理這些例外狀況，也可以利用 <xref:System.Activities.Statements.Rethrow> 活動重新擲回。</span><span class="sxs-lookup"><span data-stu-id="38c3d-104">These exceptions can be handled or they can be re-thrown using the <xref:System.Activities.Statements.Rethrow> activity.</span></span> <span data-ttu-id="38c3d-105"><xref:System.Activities.Statements.TryCatch.Finally%2A> 區段中的活動是在 <xref:System.Activities.Statements.TryCatch.Try%2A> 區段或 <xref:System.Activities.Statements.TryCatch.Catches%2A> 區段完成時執行的。</span><span class="sxs-lookup"><span data-stu-id="38c3d-105">Activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section completes.</span></span> <span data-ttu-id="38c3d-106">實例所裝載的工作流程 <xref:System.Activities.WorkflowApplication> 也可以使用 <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> 事件處理常式來處理未由活動處理的例外 <xref:System.Activities.Statements.TryCatch> 狀況。</span><span class="sxs-lookup"><span data-stu-id="38c3d-106">Workflows hosted by a <xref:System.Activities.WorkflowApplication> instance can also use the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> event handler to handle exceptions that are not handled by a <xref:System.Activities.Statements.TryCatch> activity.</span></span>  
  
## <a name="causes-of-exceptions"></a><span data-ttu-id="38c3d-107">例外狀況的原因</span><span class="sxs-lookup"><span data-stu-id="38c3d-107">Causes of Exceptions</span></span>  

 <span data-ttu-id="38c3d-108">在工作流程中，例外狀況會發生在下列情況：</span><span class="sxs-lookup"><span data-stu-id="38c3d-108">In a workflow, exceptions can be generated in the following ways:</span></span>  
  
- <span data-ttu-id="38c3d-109"><xref:System.Activities.Statements.TransactionScope> 中的交易逾時。</span><span class="sxs-lookup"><span data-stu-id="38c3d-109">A time-out of transactions in <xref:System.Activities.Statements.TransactionScope>.</span></span>  
  
- <span data-ttu-id="38c3d-110">工作流程使用 <xref:System.Activities.Statements.Throw> 活動擲回明確的例外狀況。</span><span class="sxs-lookup"><span data-stu-id="38c3d-110">An explicit exception thrown by the workflow using the <xref:System.Activities.Statements.Throw> activity.</span></span>  
  
- <span data-ttu-id="38c3d-111">活動擲回 [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] 例外狀況。</span><span class="sxs-lookup"><span data-stu-id="38c3d-111">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] exception thrown from an activity.</span></span>  
  
- <span data-ttu-id="38c3d-112">從外部程式碼 (例如程式庫、元件或工作流程中使用的服務) 擲回例外狀況。</span><span class="sxs-lookup"><span data-stu-id="38c3d-112">An exception thrown from external code, such as libraries, components, or services that are used in the workflow.</span></span>  
  
## <a name="handling-exceptions"></a><span data-ttu-id="38c3d-113">例外狀況處理</span><span class="sxs-lookup"><span data-stu-id="38c3d-113">Handling Exceptions</span></span>  

 <span data-ttu-id="38c3d-114">如果活動擲回例外狀況，且該例外狀況未經處理，預設的行為是終止該工作流程執行個體。</span><span class="sxs-lookup"><span data-stu-id="38c3d-114">If an exception is thrown by an activity and is unhandled, the default behavior is to terminate the workflow instance.</span></span> <span data-ttu-id="38c3d-115">如果自訂的 <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> 處理常式存在，即可覆寫這個預設行為。</span><span class="sxs-lookup"><span data-stu-id="38c3d-115">If a custom <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is present, it can override this default behavior.</span></span> <span data-ttu-id="38c3d-116">這個處理常式可讓工作流程主機作者提供適當的處理，例如自訂登入、中止工作流程、取消工作流程，或者終止工作流程。</span><span class="sxs-lookup"><span data-stu-id="38c3d-116">This handler gives the workflow host author an opportunity to provide the appropriate handling, such as custom logging, aborting the workflow, canceling the workflow, or terminating the workflow.</span></span>  <span data-ttu-id="38c3d-117">如果工作流程引發未處理的例外狀況，則會叫用 <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> 處理常式。</span><span class="sxs-lookup"><span data-stu-id="38c3d-117">If a workflow raises an exception that is not handled, the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="38c3d-118"><xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> 會傳回三種可能的動作，這些動作決定工作流程最終的結果。</span><span class="sxs-lookup"><span data-stu-id="38c3d-118">There are three possible actions returned from <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> which determine the final outcome of the workflow.</span></span>  
  
- <span data-ttu-id="38c3d-119">**取消** -已取消的工作流程實例是分支執行的正常結束。</span><span class="sxs-lookup"><span data-stu-id="38c3d-119">**Cancel** - A cancelled workflow instance is a graceful exit of a branch execution.</span></span> <span data-ttu-id="38c3d-120">您可以建立取消行為模型 (例如使用 CancellationScope 活動)。</span><span class="sxs-lookup"><span data-stu-id="38c3d-120">You can model cancelation behavior (for example, by using a CancellationScope activity).</span></span> <span data-ttu-id="38c3d-121">取消流程完成時，將叫用 Completed 處理常式。</span><span class="sxs-lookup"><span data-stu-id="38c3d-121">The Completed handler is invoked when the cancellation process completes.</span></span> <span data-ttu-id="38c3d-122">取消的工作流程處於 Cancelled 狀態。</span><span class="sxs-lookup"><span data-stu-id="38c3d-122">A cancelled workflow is in the Cancelled state.</span></span>  
  
- <span data-ttu-id="38c3d-123">**終止** -無法繼續或重新開機已終止的工作流程實例。</span><span class="sxs-lookup"><span data-stu-id="38c3d-123">**Terminate** - A terminated workflow instance cannot be resumed or restarted.</span></span>  <span data-ttu-id="38c3d-124">這個動作會觸發 Completed 事件，您可在其中提供例外狀況說明終止原因。</span><span class="sxs-lookup"><span data-stu-id="38c3d-124">This triggers the Completed event in which you can provide an exception as the reason it was terminated.</span></span> <span data-ttu-id="38c3d-125">終止流程完成時，將叫用 Terminated 處理常式。</span><span class="sxs-lookup"><span data-stu-id="38c3d-125">The Terminated handler is invoked when the termination process completes.</span></span> <span data-ttu-id="38c3d-126">終止的工作流程處於 Faulted 狀態。</span><span class="sxs-lookup"><span data-stu-id="38c3d-126">A terminated workflow is in the Faulted state.</span></span>  
  
- <span data-ttu-id="38c3d-127">**Abort** -已中止的工作流程實例只有在已設定為持續時才能繼續。</span><span class="sxs-lookup"><span data-stu-id="38c3d-127">**Abort** - An aborted workflow instances can be resumed only if it has been configured to be persistent.</span></span>  <span data-ttu-id="38c3d-128">沒有持續性就不能恢復工作流程。</span><span class="sxs-lookup"><span data-stu-id="38c3d-128">Without persistence, a workflow cannot be resumed.</span></span>  <span data-ttu-id="38c3d-129">工作流程中止時，會失去上一個持續點以來 (在記憶體中) 完成的所有工作。</span><span class="sxs-lookup"><span data-stu-id="38c3d-129">At the point a workflow is aborted, any work done (in memory) since the last persistence point will be lost.</span></span> <span data-ttu-id="38c3d-130">若為中止的工作流程，會在中止程序完成時使用例外狀況叫用 Aborted 處理常式說明原因。</span><span class="sxs-lookup"><span data-stu-id="38c3d-130">For an aborted workflow, the Aborted handler is invoked using the exception as the reason when the abort process completes.</span></span> <span data-ttu-id="38c3d-131">不過，Completed 不同於 Cancelled 和 Terminated 之處在於它不會被叫用。</span><span class="sxs-lookup"><span data-stu-id="38c3d-131">However, unlike Cancelled and Terminated, the Completed handler is not invoked.</span></span> <span data-ttu-id="38c3d-132">中止的工作流程處於 Aborted 狀態。</span><span class="sxs-lookup"><span data-stu-id="38c3d-132">An aborted workflow is in an Aborted state.</span></span>  
  
 <span data-ttu-id="38c3d-133">下列範例會叫用擲回例外狀況的工作流程。</span><span class="sxs-lookup"><span data-stu-id="38c3d-133">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="38c3d-134">此例外狀況未由工作流程處理，而且叫用了 <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> 處理常式。</span><span class="sxs-lookup"><span data-stu-id="38c3d-134">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="38c3d-135">系統會檢查 <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> 以提供例外狀況的相關資訊，並且終止工作流程。</span><span class="sxs-lookup"><span data-stu-id="38c3d-135">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#1](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#1)]  
  
### <a name="handling-exceptions-with-the-trycatch-activity"></a><span data-ttu-id="38c3d-136">利用 TryCatch 活動處理例外狀況</span><span class="sxs-lookup"><span data-stu-id="38c3d-136">Handling Exceptions with the TryCatch Activity</span></span>  

 <span data-ttu-id="38c3d-137">工作流程內部的例外狀況是利用 <xref:System.Activities.Statements.TryCatch> 活動進行處理。</span><span class="sxs-lookup"><span data-stu-id="38c3d-137">Handling exceptions inside a workflow is performed with the <xref:System.Activities.Statements.TryCatch> activity.</span></span> <span data-ttu-id="38c3d-138"><xref:System.Activities.Statements.TryCatch> 活動包含 <xref:System.Activities.Statements.TryCatch.Catches%2A> 活動的 <xref:System.Activities.Statements.Catch> 集合，其中每個活動各與一個特定的 <xref:System.Exception> 型別相關聯。</span><span class="sxs-lookup"><span data-stu-id="38c3d-138">The <xref:System.Activities.Statements.TryCatch> activity has a <xref:System.Activities.Statements.TryCatch.Catches%2A> collection of <xref:System.Activities.Statements.Catch> activities that are each associated with a specific <xref:System.Exception> type.</span></span> <span data-ttu-id="38c3d-139">如果活動包含在 <xref:System.Activities.Statements.TryCatch.Try%2A> 活動的 <xref:System.Activities.Statements.TryCatch> 區段中，當此活動擲回的例外狀況符合 <xref:System.Activities.Statements.Catch%601> 集合中 <xref:System.Activities.Statements.TryCatch.Catches%2A> 活動的例外狀況時，該例外狀況就會受到處理。</span><span class="sxs-lookup"><span data-stu-id="38c3d-139">If the exception thrown by an activity that is contained in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> activity matches the exception of a <xref:System.Activities.Statements.Catch%601> activity in the <xref:System.Activities.Statements.TryCatch.Catches%2A> collection, then the exception is handled.</span></span> <span data-ttu-id="38c3d-140">如果例外狀況遭到明確重新擲回，或者擲回了新的例外狀況，則會將這個例外狀況向上傳遞父活動。</span><span class="sxs-lookup"><span data-stu-id="38c3d-140">If the exception is explicitly re-thrown or a new exception is thrown then this exception passes up to the parent activity.</span></span> <span data-ttu-id="38c3d-141">下列程式碼範例示範 <xref:System.Activities.Statements.TryCatch> 活動，此活動會處理 <xref:System.ApplicationException> 活動在 <xref:System.Activities.Statements.TryCatch.Try%2A> 區段中擲回的 <xref:System.Activities.Statements.Throw>。</span><span class="sxs-lookup"><span data-stu-id="38c3d-141">The following code example shows a <xref:System.Activities.Statements.TryCatch> activity that handles an <xref:System.ApplicationException> that is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section by a <xref:System.Activities.Statements.Throw> activity.</span></span> <span data-ttu-id="38c3d-142"><xref:System.Activities.Statements.Catch%601> 活動會將例外狀況的訊息寫入至主控台，然後將訊息寫入至主控台的 <xref:System.Activities.Statements.TryCatch.Finally%2A> 區段中。</span><span class="sxs-lookup"><span data-stu-id="38c3d-142">The exception's message is written to the console by the <xref:System.Activities.Statements.Catch%601> activity, and then a message is written to the console in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#33](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#33)]  
  
 <span data-ttu-id="38c3d-143"><xref:System.Activities.Statements.TryCatch.Finally%2A> 區段中的活動會在 <xref:System.Activities.Statements.TryCatch.Try%2A> 區段或 <xref:System.Activities.Statements.TryCatch.Catches%2A> 區段順利完成時執行。</span><span class="sxs-lookup"><span data-stu-id="38c3d-143">The activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes.</span></span> <span data-ttu-id="38c3d-144">如果 <xref:System.Activities.Statements.TryCatch.Try%2A> 區段未擲回任何例外狀況，就會順利完成，如果未擲回或重新擲回任何例外狀況，則 <xref:System.Activities.Statements.TryCatch.Catches%2A> 區段也會順利完成。</span><span class="sxs-lookup"><span data-stu-id="38c3d-144">The <xref:System.Activities.Statements.TryCatch.Try%2A> section successfully completes if no exceptions are thrown from it, and the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes if no exceptions are thrown or rethrown from it.</span></span> <span data-ttu-id="38c3d-145">如果 <xref:System.Activities.Statements.TryCatch.Try%2A> 的 <xref:System.Activities.Statements.TryCatch> 區段擲回例外狀況，且未經 <xref:System.Activities.Statements.Catch%601> 區段中的 <xref:System.Activities.Statements.TryCatch.Catches%2A> 處理，或由 <xref:System.Activities.Statements.TryCatch.Catches%2A> 重新擲回，則不會執行 <xref:System.Activities.Statements.TryCatch.Finally%2A> 中的活動，除非發生下列其中任一情況。</span><span class="sxs-lookup"><span data-stu-id="38c3d-145">If an exception is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> and is either not handled by a <xref:System.Activities.Statements.Catch%601> in the <xref:System.Activities.Statements.TryCatch.Catches%2A> section, or is rethrown from the <xref:System.Activities.Statements.TryCatch.Catches%2A>, the activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> will not be executed unless the one of the following occurs.</span></span>  
  
- <span data-ttu-id="38c3d-146">工作流程中層級較高的 <xref:System.Activities.Statements.TryCatch> 活動攔截該例外狀況，而不論該例外狀況是否由該層級較高的 <xref:System.Activities.Statements.TryCatch> 重新擲回。</span><span class="sxs-lookup"><span data-stu-id="38c3d-146">The exception is caught by a higher level <xref:System.Activities.Statements.TryCatch> activity in the workflow, regardless of whether it is rethrown from that higher level <xref:System.Activities.Statements.TryCatch>.</span></span>  
  
- <span data-ttu-id="38c3d-147">該例外狀況未經層級較高的 <xref:System.Activities.Statements.TryCatch> 處理、溢出工作流程的根目錄，且該工作流程設定為取消而非終止或中止。</span><span class="sxs-lookup"><span data-stu-id="38c3d-147">The exception is not handled by a higher level <xref:System.Activities.Statements.TryCatch>, escapes the root of the workflow, and the workflow is configured to cancel instead of terminate or abort.</span></span> <span data-ttu-id="38c3d-148">使用 <xref:System.Activities.WorkflowApplication> 裝載的工作流程可以透過處理 <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> 及傳回 <xref:System.Activities.UnhandledExceptionAction.Cancel> 進行此設定。</span><span class="sxs-lookup"><span data-stu-id="38c3d-148">Workflows hosted using <xref:System.Activities.WorkflowApplication> can configure this by handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> and returning <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="38c3d-149">本主題前文亦提供處理 <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> 的範例。</span><span class="sxs-lookup"><span data-stu-id="38c3d-149">An example of handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> is provided previously in this topic.</span></span> <span data-ttu-id="38c3d-150">工作流服務可以使用 <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> 並指定 <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel> 來進行此設定。</span><span class="sxs-lookup"><span data-stu-id="38c3d-150">Workflow services can configure this by using <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> and specifying <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="38c3d-151">如需設定的範例 <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> ，請參閱 [工作流程服務主機](../wcf/feature-details/workflow-service-host-extensibility.md)擴充性。</span><span class="sxs-lookup"><span data-stu-id="38c3d-151">For an example of configuring <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, see [Workflow Service Host Extensibility](../wcf/feature-details/workflow-service-host-extensibility.md).</span></span>  
  
## <a name="exception-handling-versus-compensation"></a><span data-ttu-id="38c3d-152">例外狀況處理與補償</span><span class="sxs-lookup"><span data-stu-id="38c3d-152">Exception Handling versus Compensation</span></span>  

 <span data-ttu-id="38c3d-153">例外狀況處理與補償之間的不同在於，例外狀況處理會發生於活動執行期間。</span><span class="sxs-lookup"><span data-stu-id="38c3d-153">The difference between exception handling and compensation is that exception handling occurs during the execution of an activity.</span></span> <span data-ttu-id="38c3d-154">補償則是發生於活動順利完成後。</span><span class="sxs-lookup"><span data-stu-id="38c3d-154">Compensation occurs after an activity has successfully completed.</span></span> <span data-ttu-id="38c3d-155">例外狀況處理可讓您在活動引發例外狀況後進行清理，而補償則提供一種機制，利用這種機制即可復原先前完成之活動順利完成的工作。</span><span class="sxs-lookup"><span data-stu-id="38c3d-155">Exception handling provides an opportunity to clean up after the activity raises the exception, whereas compensation provides a mechanism by which the successfully completed work of a previously completed activity can be undone.</span></span> <span data-ttu-id="38c3d-156">如需詳細資訊，請參閱 [補償](compensation.md)。</span><span class="sxs-lookup"><span data-stu-id="38c3d-156">For more information, see [Compensation](compensation.md).</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="38c3d-157">另請參閱</span><span class="sxs-lookup"><span data-stu-id="38c3d-157">See also</span></span>

- <xref:System.Activities.Statements.TryCatch>
- <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>
- <xref:System.Activities.Statements.CompensableActivity>
