---
title: 例外狀況與例外狀況處理 - C# 程式設計手冊
description: '瞭解例外狀況和例外狀況處理。 這些 c # 功能有助於處理常式正在執行時所發生的非預期或例外狀況。'
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 4be327be4e183d60e440358254aeb9c68fcf25ca
ms.sourcegitcommit: 6f58a5f75ceeb936f8ee5b786e9adb81a9a3bee9
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 07/28/2020
ms.locfileid: "87303383"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="5d49a-104">例外狀況和例外處理 (C# 程式設計手冊)</span><span class="sxs-lookup"><span data-stu-id="5d49a-104">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="5d49a-105">C# 語言的例外狀況處理功能可協助您處理在程式執行時發生的任何未預期或例外狀況。</span><span class="sxs-lookup"><span data-stu-id="5d49a-105">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="5d49a-106">例外狀況處理會使用 `try`、`catch` 和 `finally` 關鍵字來嘗試可能失敗的動作，以便在您決定這樣做很合理時處理失敗，之後再清除資源。</span><span class="sxs-lookup"><span data-stu-id="5d49a-106">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="5d49a-107">例外狀況可由 common language runtime （CLR）、.NET 或協力廠商程式庫或應用程式代碼產生。</span><span class="sxs-lookup"><span data-stu-id="5d49a-107">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="5d49a-108">例外狀況是使用 `throw` 關鍵字所建立。</span><span class="sxs-lookup"><span data-stu-id="5d49a-108">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="5d49a-109">在許多情況下，例外狀況可能不是由您的程式碼直接呼叫的方法所擲回，而是由呼叫堆疊中更下方的另一個方法所擲回。</span><span class="sxs-lookup"><span data-stu-id="5d49a-109">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="5d49a-110">發生這種情況時，CLR 將回溯堆疊，針對特定的例外狀況型別尋找具有 `catch` 區塊的方法，而它將會執行第一個這類 `catch` 區塊 (如果找到)。</span><span class="sxs-lookup"><span data-stu-id="5d49a-110">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="5d49a-111">如果在呼叫堆疊中的任何地方都找不到適當的 `catch` 區塊，它將會終止處理序，並向使用者顯示一則訊息。</span><span class="sxs-lookup"><span data-stu-id="5d49a-111">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="5d49a-112">在此範例中，方法會測試除數為零，並攔截錯誤。</span><span class="sxs-lookup"><span data-stu-id="5d49a-112">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="5d49a-113">如果沒有例外狀況處理，此程式就會終止並產生 **DivideByZeroException 未處理**的錯誤。</span><span class="sxs-lookup"><span data-stu-id="5d49a-113">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="5d49a-114">例外狀況概觀</span><span class="sxs-lookup"><span data-stu-id="5d49a-114">Exceptions Overview</span></span>

<span data-ttu-id="5d49a-115">例外狀況具有下列屬性：</span><span class="sxs-lookup"><span data-stu-id="5d49a-115">Exceptions have the following properties:</span></span>

- <span data-ttu-id="5d49a-116">例外狀況是最終全都衍生自 `System.Exception` 的型別。</span><span class="sxs-lookup"><span data-stu-id="5d49a-116">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="5d49a-117">在可能擲回例外狀況的陳述式前後使用 `try` 區塊。</span><span class="sxs-lookup"><span data-stu-id="5d49a-117">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="5d49a-118">一旦 `try` 區塊中發生例外狀況之後，控制流程就會跳至第一個相關聯的例外狀況處理常式，此處理常式存在於呼叫堆疊中的任何位置。</span><span class="sxs-lookup"><span data-stu-id="5d49a-118">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="5d49a-119">在 C# 中，`catch` 關鍵字是用來定義例外狀況處理常式。</span><span class="sxs-lookup"><span data-stu-id="5d49a-119">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="5d49a-120">如果沒有指定例外狀況的例外狀況處理常式存在，程式就會停止執行並出現錯誤訊息。</span><span class="sxs-lookup"><span data-stu-id="5d49a-120">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="5d49a-121">除非您可以處理它，否則不要攔截例外狀況，並讓應用程式保持已知的狀態。</span><span class="sxs-lookup"><span data-stu-id="5d49a-121">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="5d49a-122">如果您攔截 `System.Exception` ，請使用區塊結尾的關鍵字重新擲回 `throw` `catch` 。</span><span class="sxs-lookup"><span data-stu-id="5d49a-122">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="5d49a-123">如果 `catch` 區塊定義了例外狀況變數，您可以使用它來取得所發生例外狀況型別的詳細資訊。</span><span class="sxs-lookup"><span data-stu-id="5d49a-123">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="5d49a-124">例外狀況可以透過程式使用 `throw` 關鍵字明確地產生。</span><span class="sxs-lookup"><span data-stu-id="5d49a-124">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="5d49a-125">例外狀況物件包含錯誤的詳細資訊，例如呼叫堆疊的狀態和錯誤狀態的文字描述。</span><span class="sxs-lookup"><span data-stu-id="5d49a-125">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="5d49a-126">即使擲回例外狀況，`finally` 區塊中的程式碼也會執行。</span><span class="sxs-lookup"><span data-stu-id="5d49a-126">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="5d49a-127">使用 `finally` 區塊來釋放資源，例如，關閉已在 `try` 區塊中開啟的任何資料流或檔案。</span><span class="sxs-lookup"><span data-stu-id="5d49a-127">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="5d49a-128">.NET 中的 Managed 例外狀況會在 Win32 結構化例外狀況處理機制之上執行。</span><span class="sxs-lookup"><span data-stu-id="5d49a-128">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="5d49a-129">如需詳細資訊，請參閱[結構化例外狀況處理 (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) 和[深入探究 Win32 結構化例外狀況處理的毀損課程 (英文)](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm)。</span><span class="sxs-lookup"><span data-stu-id="5d49a-129">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="5d49a-130">相關章節</span><span class="sxs-lookup"><span data-stu-id="5d49a-130">Related Sections</span></span>

<span data-ttu-id="5d49a-131">如需例外狀況和例外狀況處理的詳細資訊，請參閱下列文章：</span><span class="sxs-lookup"><span data-stu-id="5d49a-131">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="5d49a-132">使用例外狀況</span><span class="sxs-lookup"><span data-stu-id="5d49a-132">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="5d49a-133">例外狀況處理</span><span class="sxs-lookup"><span data-stu-id="5d49a-133">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="5d49a-134">建立和擲回例外狀況</span><span class="sxs-lookup"><span data-stu-id="5d49a-134">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="5d49a-135">編譯器所產生的例外狀況</span><span class="sxs-lookup"><span data-stu-id="5d49a-135">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="5d49a-136">如何使用 try/catch 處理例外狀況（c # 程式設計手冊）</span><span class="sxs-lookup"><span data-stu-id="5d49a-136">How to handle an exception using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="5d49a-137">如何使用 finally 執行清除程式碼</span><span class="sxs-lookup"><span data-stu-id="5d49a-137">How to execute cleanup code using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="5d49a-138">如何攔截非 CLS 例外狀況</span><span class="sxs-lookup"><span data-stu-id="5d49a-138">How to catch a non-CLS exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="5d49a-139">C# 語言規格</span><span class="sxs-lookup"><span data-stu-id="5d49a-139">C# Language Specification</span></span>

<span data-ttu-id="5d49a-140">如需詳細資訊，請參閱 [C# 語言規格](/dotnet/csharp/language-reference/language-specification/introduction)中的[例外狀況](~/_csharplang/spec/exceptions.md)。</span><span class="sxs-lookup"><span data-stu-id="5d49a-140">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="5d49a-141">語言規格是 C# 語法及用法的限定來源。</span><span class="sxs-lookup"><span data-stu-id="5d49a-141">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="5d49a-142">另請參閱</span><span class="sxs-lookup"><span data-stu-id="5d49a-142">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="5d49a-143">C # 程式設計指南</span><span class="sxs-lookup"><span data-stu-id="5d49a-143">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="5d49a-144">C # 關鍵字</span><span class="sxs-lookup"><span data-stu-id="5d49a-144">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="5d49a-145">throw</span><span class="sxs-lookup"><span data-stu-id="5d49a-145">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="5d49a-146">try-catch</span><span class="sxs-lookup"><span data-stu-id="5d49a-146">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="5d49a-147">try-finally</span><span class="sxs-lookup"><span data-stu-id="5d49a-147">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="5d49a-148">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="5d49a-148">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="5d49a-149">例外狀況</span><span class="sxs-lookup"><span data-stu-id="5d49a-149">Exceptions</span></span>](../../../standard/exceptions/index.md)
