---
title: 例外狀況與例外狀況處理 - C# 程式設計手冊
description: '瞭解例外狀況和例外狀況處理。 這些 c # 功能有助於處理常式執行時所發生的非預期或例外狀況。'
ms.date: 12/09/2020
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 679171e6d397741ef44cb37fb770f6feba039fd9
ms.sourcegitcommit: 9b877e160c326577e8aa5ead22a937110d80fa44
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 12/11/2020
ms.locfileid: "97110620"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="07ba1-104">例外狀況和例外處理 (C# 程式設計手冊)</span><span class="sxs-lookup"><span data-stu-id="07ba1-104">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="07ba1-105">C# 語言的例外狀況處理功能可協助您處理在程式執行時發生的任何未預期或例外狀況。</span><span class="sxs-lookup"><span data-stu-id="07ba1-105">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="07ba1-106">例外狀況處理 `try` 會使用、 `catch` 和 `finally` 關鍵字來嘗試可能不會成功的動作，以便在您決定是否合理進行時處理失敗，並在之後清除資源。</span><span class="sxs-lookup"><span data-stu-id="07ba1-106">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it's reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="07ba1-107">例外狀況可由 common language runtime (CLR) 、.NET 或協力廠商程式庫，或應用程式程式碼產生。</span><span class="sxs-lookup"><span data-stu-id="07ba1-107">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="07ba1-108">例外狀況是使用 `throw` 關鍵字所建立。</span><span class="sxs-lookup"><span data-stu-id="07ba1-108">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="07ba1-109">在許多情況下，例外狀況可能不是由您的程式碼直接呼叫的方法所擲回，而是由呼叫堆疊中更下方的另一個方法所擲回。</span><span class="sxs-lookup"><span data-stu-id="07ba1-109">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="07ba1-110">當擲回例外狀況時，CLR 會回溯堆疊，尋找具有 `catch` 特定例外狀況類型之區塊的方法，並執行第一個這類 `catch` 區塊（如果找到的話）。</span><span class="sxs-lookup"><span data-stu-id="07ba1-110">When an exception is thrown happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="07ba1-111">如果在呼叫堆疊中的任何地方都找不到適當的 `catch` 區塊，它將會終止處理序，並向使用者顯示一則訊息。</span><span class="sxs-lookup"><span data-stu-id="07ba1-111">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="07ba1-112">在此範例中，方法會測試除數為零，並攔截錯誤。</span><span class="sxs-lookup"><span data-stu-id="07ba1-112">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="07ba1-113">如果沒有例外狀況處理，此程式就會終止並產生 **DivideByZeroException 未處理** 的錯誤。</span><span class="sxs-lookup"><span data-stu-id="07ba1-113">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

:::code language="csharp" source="snippets/exceptions/ExceptionTest.cs" ID="ExceptionTest":::

## <a name="exceptions-overview"></a><span data-ttu-id="07ba1-114">例外狀況概觀</span><span class="sxs-lookup"><span data-stu-id="07ba1-114">Exceptions Overview</span></span>

<span data-ttu-id="07ba1-115">例外狀況具有下列屬性：</span><span class="sxs-lookup"><span data-stu-id="07ba1-115">Exceptions have the following properties:</span></span>

- <span data-ttu-id="07ba1-116">例外狀況是最終全都衍生自 `System.Exception` 的型別。</span><span class="sxs-lookup"><span data-stu-id="07ba1-116">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="07ba1-117">在可能擲回例外狀況的陳述式前後使用 `try` 區塊。</span><span class="sxs-lookup"><span data-stu-id="07ba1-117">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="07ba1-118">一旦 `try` 區塊中發生例外狀況之後，控制流程就會跳至第一個相關聯的例外狀況處理常式，此處理常式存在於呼叫堆疊中的任何位置。</span><span class="sxs-lookup"><span data-stu-id="07ba1-118">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="07ba1-119">在 C# 中，`catch` 關鍵字是用來定義例外狀況處理常式。</span><span class="sxs-lookup"><span data-stu-id="07ba1-119">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="07ba1-120">如果沒有指定例外狀況的例外狀況處理常式存在，程式就會停止執行並出現錯誤訊息。</span><span class="sxs-lookup"><span data-stu-id="07ba1-120">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="07ba1-121">除非您可以處理例外狀況，並讓應用程式處於已知狀態，否則請勿攔截例外狀況。</span><span class="sxs-lookup"><span data-stu-id="07ba1-121">Don't catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="07ba1-122">如果您攔截 `System.Exception`，請在 `catch` 區塊結尾使用 `throw` 關鍵字重新擲回它。</span><span class="sxs-lookup"><span data-stu-id="07ba1-122">If you catch `System.Exception`, rethrow it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="07ba1-123">如果 `catch` 區塊定義了例外狀況變數，您可以使用它來取得所發生例外狀況型別的詳細資訊。</span><span class="sxs-lookup"><span data-stu-id="07ba1-123">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="07ba1-124">例外狀況可以透過程式使用 `throw` 關鍵字明確地產生。</span><span class="sxs-lookup"><span data-stu-id="07ba1-124">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="07ba1-125">例外狀況物件包含錯誤的詳細資訊，例如呼叫堆疊的狀態和錯誤狀態的文字描述。</span><span class="sxs-lookup"><span data-stu-id="07ba1-125">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="07ba1-126">即使擲回例外狀況，`finally` 區塊中的程式碼也會執行。</span><span class="sxs-lookup"><span data-stu-id="07ba1-126">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="07ba1-127">使用 `finally` 區塊來釋放資源，例如，關閉已在 `try` 區塊中開啟的任何資料流或檔案。</span><span class="sxs-lookup"><span data-stu-id="07ba1-127">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="07ba1-128">.NET 中的 Managed 例外狀況會在 Win32 結構化例外狀況處理機制之上執行。</span><span class="sxs-lookup"><span data-stu-id="07ba1-128">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="07ba1-129">如需詳細資訊，請參閱[結構化例外狀況處理 (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) 和[深入探究 Win32 結構化例外狀況處理的毀損課程 (英文)](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm)。</span><span class="sxs-lookup"><span data-stu-id="07ba1-129">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="c-language-specification"></a><span data-ttu-id="07ba1-130">C# 語言規格</span><span class="sxs-lookup"><span data-stu-id="07ba1-130">C# Language Specification</span></span>

<span data-ttu-id="07ba1-131">如需詳細資訊，請參閱 [C# 語言規格](/dotnet/csharp/language-reference/language-specification/introduction)中的[例外狀況](~/_csharplang/spec/exceptions.md)。</span><span class="sxs-lookup"><span data-stu-id="07ba1-131">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="07ba1-132">語言規格是 C# 語法及用法的限定來源。</span><span class="sxs-lookup"><span data-stu-id="07ba1-132">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="07ba1-133">另請參閱</span><span class="sxs-lookup"><span data-stu-id="07ba1-133">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="07ba1-134">C # 關鍵字</span><span class="sxs-lookup"><span data-stu-id="07ba1-134">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="07ba1-135">扔</span><span class="sxs-lookup"><span data-stu-id="07ba1-135">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="07ba1-136">try-catch</span><span class="sxs-lookup"><span data-stu-id="07ba1-136">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="07ba1-137">try-finally</span><span class="sxs-lookup"><span data-stu-id="07ba1-137">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="07ba1-138">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="07ba1-138">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="07ba1-139">例外狀況</span><span class="sxs-lookup"><span data-stu-id="07ba1-139">Exceptions</span></span>](../../../standard/exceptions/index.md)
